apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/crawler
            - name: RABBITMQ_URL
              value: amqp://rabbitmq
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
          volumeMounts:
            - name: results-volume
              mountPath: /app/results
      volumes:
        - name: results-volume
          persistentVolumeClaim:
            claimName: results-pvc
